name: On Github Release is publised

# This github action call the release pipeline workflow which includes
# the deployment of the latest version of this repository.

on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  call_release_pipeline:
    name: Run release pipeline
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPATECE, so your job can access it
      - name: Run release pipeline workflow
        run: |
          curl -X POST https://api.github.com/repos/cesiztel/reusable-workflow/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.REPO_ACCESS_TOKEN }} \
          --data '{"event_type": "reusable-workflow-caller"}'
      - uses: actions/checkout@v3