  on:
    push:
      branches:
        - main
      # Sequence of patterns matched against refs/tags
      # tags:
      #  - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  name: Create Github release after tag releasable code

  jobs:
    create_release:
      name: Create Github release
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Build Changelog
          id: github_release
          run: |
            # Start building change log
            # 1. Get the previous tag
            REV_LIST=`git rev-list --tags --skip=1 --max-count=1`
            echo $REV_LIST
            # PREVIOUS_TAG=`git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1)`
            # PR_RELEASE=`git log --merges --grep 'Merge pull request' --pretty=format:%s $PREVIOUS_TAG..${{github.ref}} | grep -o '#[0-9]*'`
             
            # echo $PREVIOUS_TAG
            # echo $PR_RELEASE
          shell: bash
        
        - name: Create Release
          uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
          with:
            body: ${{steps.github_release.outputs.release_notes}}