  on:
    push:
      # Sequence of patterns matched against refs/tags
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      branches:
        - main

  name: Create Github release after tag releasable code
   
  jobs:
    building_change_log:
      name: Building change log
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Build Changelog
          id: build_changelog
          run: |
            # Start building change log
            # 1. Get the previous tag
            REV_LIST=`git rev-list --tags --skip=1 --max-count=1`
            echo $REV_LIST
            PREVIOUS_TAG=`git describe --abbrev=0 --tags $REV_LIST`
            echo $PREVIOUS_TAG
            PR_RELEASE=`git log --merges --grep 'Merge pull request' --pretty=format:%s $PREVIOUS_TAG..${{github.ref}} | grep -o '#[0-9]*'`
             
            # List of the PRS of the release $PR_RELEASE
            # Preparing notes template"
            echo $PR_RELEASE
            NOTES="User story | Description \n -- | -- \n"
            echo $NOTES
            # Looping over releaseses to get the data
            for pr_number in $PR_RELEASE
            do
              pr_number=${pr_number:1}
              echo $pr_number
              change_log_entry_title=`gh pr view $pr_number | head -n 1`
              echo $change_log_entry_title
              last_element=${change_log_entry_title##*:}
              echo $last_element
              NOTES="$NOTES \n $last_element"
            done
            
            echo $NOTES
            # Preparing output
            echo "release_notes=$NOTES" >> "$GITHUB_OUTPUT"
          shell: bash
          env: 
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    create_release:
      name: Create Github release
      runs-on: ubuntu-latest
      needs: building_change_log
      steps:
        - name: Create Release
          uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
          with:
            body: ${{needs.building_change_log.outputs.release_notes}}