  on:
    push:
      # Sequence of patterns matched against refs/tags
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      branches:
        - main

  name: Create Github release after tag releasable code
   
  jobs:
    building_change_log:
      name: Building change log
      runs-on: ubuntu-latest
      outputs:
        release_notes: ${{ steps.build_changelog.outputs.release_notes }}
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Build Changelog
          id: build_changelog
          run: |
            # Start building change log
            # 1. Get the previous tag
            REV_LIST=`git rev-list --tags --skip=1 --max-count=1`
            PREVIOUS_TAG=`git describe --abbrev=0 --tags $REV_LIST`
            PR_RELEASE=`git log --merges --grep 'Merge pull request' --pretty=format:%s $PREVIOUS_TAG..${{github.ref}} | grep -o '#[0-9]*'`
             
            # List of the PRS of the release $PR_RELEASE
            # Preparing notes template"
            NOTES="### 🚀 Features included on the release: \n"
            # Looping over releaseses to get the data
            for pr_number in $PR_RELEASE
            do
              pr_number=${pr_number:1}
              change_log_entry_title=`gh pr view $pr_number | head -n 1`
              last_element=${change_log_entry_title##*:}
              NOTES+="* $last_element \n"
            done
            # Preparing output
            echo "MULTI_LINES_NOTES<<EOF" >> $GITHUB_OUTPUT
            echo "release_notes=$NOTES" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          shell: bash
          env: 
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    create_release:
      name: Create Github release
      runs-on: ubuntu-latest
      needs: building_change_log
      steps:
        - name: Create Release
          uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
          with:
            body: ${{needs.building_change_log.outputs.release_notes}}